# Problem Definintion.

In [ ]:
Categorising online shoppers on Kira Plastina Brand

# Data Sourcing.

In [ ]:
I sourced data from the the kira plastina website http://bit.ly/EcommerceCustomersDataset

# Libraries

In [18]:
library(tidyverse)
install.packages("DataExplorer")
library(DataExplorer)
library(caret)
library(ggplot2)
library(remotes)
library(pacman)
library(gmodels)
library(outliers)

Installing package into 'C:/Users/user/Documents/R/win-library/3.6'
(as 'lib' is unspecified)
Warning message:
"package 'DataExplorer' is in use and will not be installed"

In [3]:
#Loading the dataset
#Loading the dataset for analysis
shoppers_data<- read.csv("http://bit.ly/EcommerceCustomersDataset")

# Checking Data Information.

In [4]:
#Checkinng the dimension of the dataset
dim(shoppers_data)

[1] 12330    18

There are 12330 columns and 18 columns

In [5]:
#Checking for the names of the columns
attributes(shoppers_data)$names

 [1] "Administrative"          "Administrative_Duration"
 [3] "Informational"           "Informational_Duration"
 [5] "ProductRelated"          "ProductRelated_Duration"
 [7] "BounceRates"             "ExitRates"
 [9] "PageValues"              "SpecialDay"
[11] "Month"                   "OperatingSystems"
[13] "Browser"                 "Region"
[15] "TrafficType"             "VisitorType"
[17] "Weekend"                 "Revenue"

In [6]:
# Checking the datatypes for every column
columns = colnames(shoppers_data)
for (column in seq(length(colnames(shoppers_data)))){
    print(columns[column])
    print(class(shoppers_data[, column]))
    cat('\n')
}

[1] "Administrative"
[1] "integer"

[1] "Administrative_Duration"
[1] "numeric"

[1] "Informational"
[1] "integer"

[1] "Informational_Duration"
[1] "numeric"

[1] "ProductRelated"
[1] "integer"

[1] "ProductRelated_Duration"
[1] "numeric"

[1] "BounceRates"
[1] "numeric"

[1] "ExitRates"
[1] "numeric"

[1] "PageValues"
[1] "numeric"

[1] "SpecialDay"
[1] "numeric"

[1] "Month"
[1] "factor"

[1] "OperatingSystems"
[1] "integer"

[1] "Browser"
[1] "integer"

[1] "Region"
[1] "integer"

[1] "TrafficType"
[1] "integer"

[1] "VisitorType"
[1] "factor"

[1] "Weekend"
[1] "logical"

[1] "Revenue"
[1] "logical"

In [7]:
#Statistical summary
summary(shoppers_data)

 Administrative   Administrative_Duration Informational
 Min.   : 0.000   Min.   :  -1.00         Min.   : 0.000
 1st Qu.: 0.000   1st Qu.:   0.00         1st Qu.: 0.000
 Median : 1.000   Median :   8.00         Median : 0.000
 Mean   : 2.318   Mean   :  80.91         Mean   : 0.504
 3rd Qu.: 4.000   3rd Qu.:  93.50         3rd Qu.: 0.000
 Max.   :27.000   Max.   :3398.75         Max.   :24.000
 NA's   :14       NA's   :14              NA's   :14
 Informational_Duration ProductRelated   ProductRelated_Duration
 Min.   :  -1.00        Min.   :  0.00   Min.   :   -1.0
 1st Qu.:   0.00        1st Qu.:  7.00   1st Qu.:  185.0
 Median :   0.00        Median : 18.00   Median :  599.8
 Mean   :  34.51        Mean   : 31.76   Mean   : 1196.0
 3rd Qu.:   0.00        3rd Qu.: 38.00   3rd Qu.: 1466.5
 Max.   :2549.38        Max.   :705.00   Max.   :63973.5
 NA's   :14             NA's   :14       NA's   :14
  BounceRates         ExitRates         PageValues        SpecialDay
 Min.   :0.000000   Min.   :0.00000   Min.   :  0.000   Min.   :0.00000
 1st Qu.:0.000000   1st Qu.:0.01429   1st Qu.:  0.000   1st Qu.:0.00000
 Median :0.003119   Median :0.02512   Median :  0.000   Median :0.00000
 Mean   :0.022152   Mean   :0.04300   Mean   :  5.889   Mean   :0.06143
 3rd Qu.:0.016684   3rd Qu.:0.05000   3rd Qu.:  0.000   3rd Qu.:0.00000
 Max.   :0.200000   Max.   :0.20000   Max.   :361.764   Max.   :1.00000
 NA's   :14         NA's   :14
     Month      OperatingSystems    Browser           Region
 May    :3364   Min.   :1.000    Min.   : 1.000   Min.   :1.000
 Nov    :2998   1st Qu.:2.000    1st Qu.: 2.000   1st Qu.:1.000
 Mar    :1907   Median :2.000    Median : 2.000   Median :3.000
 Dec    :1727   Mean   :2.124    Mean   : 2.357   Mean   :3.147
 Oct    : 549   3rd Qu.:3.000    3rd Qu.: 2.000   3rd Qu.:4.000
 Sep    : 448   Max.   :8.000    Max.   :13.000   Max.   :9.000
 (Other):1337
  TrafficType               VisitorType     Weekend         Revenue
 Min.   : 1.00   New_Visitor      : 1694   Mode :logical   Mode :logical
 1st Qu.: 2.00   Other            :   85   FALSE:9462      FALSE:10422
 Median : 2.00   Returning_Visitor:10551   TRUE :2868      TRUE :1908
 Mean   : 4.07
 3rd Qu.: 4.00
 Max.   :20.00

In [8]:
#Displaying the first three rows of the dataset
shoppers_data[1:3,]

  Administrative Administrative_Duration Informational Informational_Duration
1 0               0                      0              0
2 0               0                      0              0
3 0              -1                      0             -1
  ProductRelated ProductRelated_Duration BounceRates ExitRates PageValues
1 1               0                      0.2         0.2       0
2 2              64                      0.0         0.1       0
3 1              -1                      0.2         0.2       0
  SpecialDay Month OperatingSystems Browser Region TrafficType
1 0          Feb   1                1       1      1
2 0          Feb   2                2       1      2
3 0          Feb   4                1       9      3
  VisitorType       Weekend Revenue
1 Returning_Visitor FALSE   FALSE
2 Returning_Visitor FALSE   FALSE
3 Returning_Visitor FALSE   FALSE

In [12]:
# Checking the unique values of columns that are factors 

factor.cols <- c('Month','VisitorType')
no <- function(x) {  
    levels(x)
  }
  
number <- sapply(select(shoppers_data, factor.cols), no)
number

$Month
 [1] "Aug"  "Dec"  "Feb"  "Jul"  "June" "Mar"  "May"  "Nov"  "Oct"  "Sep"

$VisitorType
[1] "New_Visitor"       "Other"             "Returning_Visitor"

In [ ]:
# Checking the unique values of columns that are numerical 

number.cols <- c('Administrative','Informational','SpecialDay','OperatingSystems','Browser','Region','TrafficType','Weekend','Revenue')
no <- function(x) {  
    unique(x)
  }
  
number <- sapply(select(shoppers_data# Checking the unique values of columns that are numerical 

num.columns <- c('Administrative','Informational','SpecialDay','OperatingSystems','Browser','Region','TrafficType','Weekend','Revenue')
no <- function(x) {  
    unique(x)
  }
  
number <- sapply(select(df, num.columns), no)
number, num.columns), no)
number

In [13]:
# Checking the unique values of columns that are numerical 

number.cols <- c('Administrative','Informational','SpecialDay','OperatingSystems','Browser','Region','TrafficType','Weekend','Revenue')
no <- function(x) {  
    unique(x)
  }
  
number <- sapply(select(shoppers_data, number.cols), no)
number

$Administrative
 [1]  0  1  2  4 12  3 10  6  5  9  8 16 13 11  7 18 14 17 19 15 NA 24 22 21 20
[26] 23 27 26

$Informational
 [1]  0  1  2  4 16  5  3 14  6 12  7 NA  9 10  8 11 24 13

$SpecialDay
[1] 0.0 0.4 0.8 1.0 0.2 0.6

$OperatingSystems
[1] 1 2 4 3 7 6 8 5

$Browser
 [1]  1  2  3  4  5  6  7 10  8  9 12 13 11

$Region
[1] 1 9 2 3 4 5 6 7 8

$TrafficType
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 18 19 16 17 20

$Weekend
[1] FALSE  TRUE

$Revenue
[1] FALSE  TRUE

In [14]:
# Summary of numeric columns

shoppers_data %>%
  select_if(is.numeric) %>%
  map(~summary(.))

$Administrative
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
  0.000   0.000   1.000   2.318   4.000  27.000      14

$Administrative_Duration
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
  -1.00    0.00    8.00   80.91   93.50 3398.75      14

$Informational
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
  0.000   0.000   0.000   0.504   0.000  24.000      14

$Informational_Duration
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
  -1.00    0.00    0.00   34.51    0.00 2549.38      14

$ProductRelated
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
   0.00    7.00   18.00   31.76   38.00  705.00      14

$ProductRelated_Duration
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
   -1.0   185.0   599.8  1196.0  1466.5 63973.5      14

$BounceRates
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's
0.000000 0.000000 0.003119 0.022152 0.016684 0.200000       14

$ExitRates
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's
0.00000 0.01429 0.02512 0.04300 0.05000 0.20000      14

$PageValues
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  0.000   0.000   0.000   5.889   0.000 361.764

$SpecialDay
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
0.00000 0.00000 0.00000 0.06143 0.00000 1.00000

$OperatingSystems
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  1.000   2.000   2.000   2.124   3.000   8.000

$Browser
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  1.000   2.000   2.000   2.357   2.000  13.000

$Region
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  1.000   1.000   3.000   3.147   4.000   9.000

$TrafficType
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   1.00    2.00    2.00    4.07    4.00   20.00

# DATA CLEANING.

In [17]:
anyDuplicate(shoppers_data)

ERROR: Error in anyDuplicate(shoppers_data): could not find function "anyDuplicate"

# EXPLORATORY DATA ANALYSIS

# SOLUTION IMPLIMENTATION